In [29]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report

In [2]:
df=pd.read_csv('/content/spam.csv')

In [3]:
df.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [6]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [7]:
df['Spam']=df['Category'].apply(lambda x:1 if x=='spam' else 0)

In [8]:
df.head()

  Category                                            Message  Spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [9]:
df.shape

(5572, 3)

In [12]:
X_train,X_test,y_train,y_test=train_test_split(df.Message,df.Spam,test_size=0.2)

In [13]:
X_train.shape

(4457,)

In [14]:
X_test.shape

(1115,)

#Create bag of words using CountVectorizer

In [16]:
v=CountVectorizer()

In [17]:
X_train_cv=v.fit_transform(X_train.values)
X_test_cv=v.transform(X_test.values)

In [18]:
X_train_cv.shape

(4457, 7726)

In [19]:
v.get_feature_names_out()

array(['00', '000', '000pes', ..., 'zoom', 'ú1', '〨ud'], dtype=object)

In [22]:
v.get_feature_names_out()[1771]

'chile'

In [23]:
v.vocabulary_

{'dhoni': 2264,
 'have': 3341,
 'luck': 4236,
 'to': 6916,
 'win': 7502,
 'some': 6265,
 'big': 1331,
 'title': 6898,
 'so': 6253,
 'we': 7403,
 'will': 7499,
 'do': 2347,
 'you': 7687,
 'always': 917,
 'celebrate': 1683,
 'ny': 4841,
 'with': 7530,
 'your': 7693,
 'family': 2747,
 'its': 3754,
 'just': 3861,
 'the': 6794,
 'effect': 2518,
 'of': 4863,
 'irritation': 3733,
 'ignore': 3593,
 'it': 3746,
 'are': 1030,
 'winner': 7512,
 'been': 1275,
 'specially': 6335,
 'selected': 5970,
 'receive': 5597,
 '1000': 249,
 'cash': 1657,
 'or': 4943,
 '2000': 340,
 'award': 1154,
 'speak': 6331,
 'live': 4135,
 'operator': 4930,
 'claim': 1803,
 'call': 1587,
 '087147123779am': 113,
 '7pm': 622,
 'cost': 2000,
 '10p': 256,
 'huh': 3529,
 'lei': 4065,
 'also': 912,
 'where': 7468,
 'piece': 5177,
 'ok': 4885,
 'how': 3505,
 'dear': 2166,
 'did': 2274,
 'chechi': 1737,
 'india': 3655,
 'going': 3155,
 'draw': 2419,
 'series': 6000,
 'after': 838,
 'many': 4332,
 'years': 7662,
 'in': 3634,
 'south': 6314,
 'african': 836,
 'soil': 6259,
 'why': 7486,
 'wake': 7341,
 'up': 7162,
 'on': 4905,
 'my': 4643,
 'own': 5004,
 'gt': 3243,
 'urgent': 7182,
 'won': 7557,
 'week': 7424,
 'free': 2963,
 'membership': 4419,
 'our': 4974,
 '100': 248,
 '000': 1,
 'prize': 5386,
 'jackpot': 3770,
 'txt': 7073,
 'word': 7572,
 'no': 4770,
 '81010': 640,
 'www': 7622,
 'dbuk': 2159,
 'net': 4718,
 'lccltd': 4038,
 'pobox': 5234,
 '4403ldnw1a7rw18': 486,
 'joy': 3844,
 'father': 2765,
 'is': 3735,
 'john': 3825,
 'then': 6806,
 'name': 4660,
 'mandan': 4324,
 'neva': 4726,
 'tell': 6732,
 'me': 4387,
 'noe': 4774,
 'not': 4801,
 'at': 1100,
 'home': 3458,
 'da': 2119,
 'aft': 837,
 'wat': 7382,
 'am': 919,
 'much': 4613,
 'for': 2919,
 'an': 942,
 '8th': 708,
 'fifty': 2811,
 'think': 6826,
 'ur': 7178,
 'smart': 6216,
 '200': 339,
 'this': 6834,
 'weekly': 7428,
 'quiz': 5504,
 'text': 6765,
 'play': 5210,
 '85222': 671,
 'now': 4811,
 'cs': 2071,
 'winnersclub': 7513,
 'po': 5232,
 'box': 1439,
 '84': 663,
 'm26': 4265,
 '3uz': 467,
 '16': 306,
 'gbp1': 3074,
 '50': 529,
 'ugh': 7095,
 'fuck': 3008,
 'resubbing': 5724,
 'eve': 2641,
 'happened': 3313,
 'cruise': 2067,
 'thing': 6824,
 'meeting': 4404,
 'sms': 6235,
 'auction': 1123,
 'brand': 1465,
 'new': 4730,
 'nokia': 4778,
 '7250': 603,
 'today': 6922,
 'join': 3826,
 'take': 6667,
 'part': 5059,
 '86021': 675,
 'hg': 3408,
 'suite342': 6559,
 '2lands': 392,
 'row': 5799,
 'w1j6hl': 7321,
 'll': 4143,
 'right': 5751,
 'later': 4021,
 'cherthala': 1754,
 'case': 1656,
 'coming': 1895,
 'cochin': 1857,
 'pls': 5225,
 'bfore': 1323,
 'start': 6415,
 'shall': 6037,
 'reach': 5561,
 'accordingly': 774,
 'which': 7474,
 'day': 2155,
 'tmorow': 6909,
 'engaged': 2575,
 'ans': 966,
 'holiday': 3453,
 'sir': 6155,
 'need': 4703,
 'axis': 1161,
 'bank': 1204,
 'account': 775,
 'and': 945,
 'address': 802,
 'flirting': 2881,
 'girl': 3121,
 'bloke': 1379,
 'age': 846,
 'eg': 2522,
 'zoe': 7721,
 '18': 311,
 '8007': 629,
 'get': 3100,
 'chatting': 1732,
 'when': 7464,
 'dad': 2123,
 'back': 1179,
 'someone': 6269,
 'know': 3951,
 'has': 3330,
 'asked': 1078,
 'dating': 2151,
 'service': 6005,
 'contact': 1961,
 'cant': 1621,
 'guess': 3252,
 'who': 7479,
 '09058091854': 164,
 'all': 898,
 'be': 1253,
 'revealed': 5738,
 'box385': 1445,
 'm6': 4268,
 '6wu': 599,
 'can': 1610,
 'that': 6790,
 'happen': 3311,
 'tonight': 6949,
 'would': 7593,
 'like': 4101,
 'see': 5959,
 'xxx': 7638,
 'pics': 5172,
 'they': 6820,
 'hot': 3493,
 'were': 7447,
 'nearly': 4695,
 'banned': 1206,
 'uk': 7100,
 'maaaan': 4274,
 'missing': 4494,
 'out': 4977,
 'yes': 7671,
 'rent': 5678,
 'very': 7255,
 'expensive': 2698,
 'way': 7398,
 'save': 5895,
 'gonna': 3164,
 'rimac': 5755,
 'access': 766,
 'thought': 6845,
 'thanks': 6782,
 'sweet': 6625,
 'dreams': 2423,
 'jst': 3847,
 'change': 1707,
 'tat': 6692,
 'only': 4916,
 'popped': 5279,
 'ask': 1076,
 'bout': 1436,
 'something': 6274,
 'she': 6052,
 'said': 5852,
 'around': 1052,
 'tonght': 6947,
 'wen': 7442,
 'comes': 1891,
 'reverse': 5740,
 'cheating': 1736,
 'mathematics': 4365,
 'lmao': 4146,
 'wont': 7564,
 'needing': 4706,
 'hair': 3283,
 'anymore': 980,
 'talking': 6678,
 'thats': 6793,
 'de': 2161,
 'any': 977,
 'other': 4968,
 're': 5560,
 'christmassy': 1793,
 'here': 3397,
 'chance': 1705,
 '250': 361,
 'every': 2650,
 'wk': 7539,
 '83370': 658,
 'music': 4633,
 'trivia': 7025,
 'custcare': 2103,
 '08715705022': 124,
 '1x150p': 336,
 'yeah': 7660,
 'impression': 3630,
 'got': 3184,
 'lovable': 4207,
 'bcums': 1250,
 'angry': 951,
 'wid': 7489,
 'dnt': 2346,
 'seriously': 6002,
 'coz': 2024,
 'being': 1291,
 'most': 4571,
 'childish': 1768,
 'true': 7032,
 'showing': 6104,
 'deep': 2188,
 'affection': 829,
 'care': 1634,
 'luv': 4249,
 'kettoda': 3908,
 'manda': 4323,
 'nice': 4743,
 'but': 1554,
 'really': 5580,
 'broke': 1502,
 'oh': 4880,
 'amount': 935,
 'too': 6954,
 'small': 6214,
 'even': 2643,
 'lt': 4231,
 'man': 4317,
 'carlos': 1646,
 'definitely': 2197,
 'by': 1571,
 'mu': 4611,
 'excuses': 2683,
 'great': 3217,
 'escape': 2622,
 'fancy': 2751,
 'bridge': 1485,
 'needs': 4708,
 'her': 3396,
 'lager': 3988,
 'tomo': 6939,
 'what': 7458,
 'yo': 7682,
 'date': 2148,
 'weird': 7434,
 'because': 1263,
 'had': 3277,
 'one': 4911,
 'point': 5252,
 'okie': 4889,
 'lor': 4188,
 'go': 3144,
 'sat': 5883,
 'compliments': 1920,
 'was': 7375,
 'away': 1156,
 'from': 3000,
 'system': 6649,
 'side': 6122,
 'quite': 5502,
 'dun': 2466,
 'him': 3418,
 'wait': 7337,
 'he': 3350,
 'complacent': 1910,
 'apps': 1019,
 'class': 1811,
 'varaya': 7230,
 'elaya': 2539,
 'rofl': 5778,
 'betta': 1312,
 'invest': 3708,
 'anti': 975,
 'aging': 854,
 'products': 5403,
 'im': 3606,
 'snowboarding': 6250,
 'trip': 7021,
 'wondering': 7562,
 'if': 3588,
 'planning': 5206,
 'everyone': 2655,
 'together': 6925,
 'befor': 1280,
 'meet': 4402,
 'greet': 3223,
 'kind': 3931,
 'affair': 827,
 'cheers': 1747,
 'people': 5111,
 'seems': 5965,
 'special': 6333,
 'first': 2852,
 'sight': 6125,
 'few': 2799,
 'remain': 5660,
 'till': 6883,
 'last': 4015,
 'maintain': 4305,
 'them': 6802,
 'life': 4091,
 'ends': 2570,
 'sh': 6026,
 'jas': 3785,
 'mobile': 4526,
 'awarded': 1155,
 'bonus': 1408,
 'caller': 1593,
 '08': 43,
 '03': 14,
 '2nd': 401,
 'attempt': 1111,
 '0871': 91,
 '4719': 499,
 '523': 543,
 'box95qu': 1451,
 'bt': 1521,
 'national': 4678,
 'rate': 5544,
 'town': 6984,
 'alone': 907,
 'doing': 2373,
 'lots': 4198,
 'used': 7198,
 'ones': 4912,
 'babe': 1171,
 'model': 4536,
 'doesn': 2361,
 'help': 3385,
 'youi': 7689,
 'bring': 1492,
 'over': 4991,
 'match': 4359,
 'hi': 3410,
 'darlin': 2140,
 'ive': 3760,
 'night': 4750,
 'lift': 4095,
 'tomorrow': 6941,
 'reason': 5585,
 'team': 6715,
 'budget': 1529,
 'available': 1139,
 'buy': 1559,
 'unsold': 7154,
 'players': 5213,
 'base': 1219,
 'themob': 6805,
 'hit': 3426,
 'link': 4118,
 'premium': 5346,
 'pink': 5187,
 'panther': 5035,
 'game': 3049,
 'sugababes': 6552,
 'crazy': 2042,
 'zebra': 7718,
 'animation': 953,
 'badass': 1182,
 'hoody': 3469,
 'wallpaper': 7352,
 'paper': 5040,
 'morn': 4566,
 'b4u': 1167,
 'voucher': 7310,
 '27': 368,
 'marsms': 4349,
 'log': 4159,
 'onto': 4918,
 'b4utele': 1168,
 'com': 1884,
 'discount': 2322,
 'credit': 2048,
 'opt': 4938,
 'reply': 5690,
 'stop': 6462,
 'customer': 2105,
 '08717168528': 126,
 'days': 2156,
 'billion': 1338,
 'classes': 1812,
 'feel': 2784,
 'words': 7573,
 'better': 1313,
 'than': 6778,
 'silence': 6132,
 'gud': 3248,
 'mrng': 4593,
 'mmmmmmm': 4517,
 'snuggles': 6252,
 'into': 3703,
 'contented': 1966,
 'sigh': 6123,
 'whispers': 7476,
 'fucking': 3011,
 'love': 4208,
 'barely': 1210,
 'stand': 6404,
 'mind': 4464,
 'bedroom': 1273,
 'minute': 4479,
 'sed': 5958,
 'sexy': 6021,
 'mood': 4561,
 'came': 1605,
 'minuts': 4481,
 'latr': 4024,
 'cake': 1579,
 'wife': 7492,
 'excellent': 2676,
 'misundrstud': 4502,
 'frnd': 2991,
 'knw': 3955,
 'hate': 3334,
 'truth': 7039,
 'urself': 7192,
 'gn': 3140,
 'cool': 1983,
 'little': 4134,
 'while': 7475,
 'getting': 3107,
 'more': 4564,
 'time': 6885,
 'soon': 6289,
 'clearly': 1822,
 'fault': 2768,
 'pretty': 5364,
 'best': 1307,
 'scenario': 5909,
 'juan': 3850,
 'fri': 2978,
 'hey': 3406,
 'course': 2018,
 'expect': 2694,
 'welcome': 7437,
 'party': 5065,
 'presents': 5356,
 'ill': 3602,
 'phone': 5157,
 'loads': 4150,
 'nicky': 4747,
 'dunno': 2467,
 'shd': 6051,
 'driving': 2435,
 'cos': 1998,
 'sch': 5911,
 'hr': 3515,
 'oni': 4913,
 'gave': 3068,
 'photo': 5161,
 'registered': 5642,
 'ah': 857,
 'tmr': 6910,
 'wanna': 7360,
 'yck': 7659,
 'wuld': 7619,
 'without': 7533,
 'baby': 1174,
 'mite': 4503,
 'break': 1474,
 'don': 2381,
 'everyboy': 2653,
 'his': 3424,
 'lady': 3985,
 'xxxxxxxx': 7644,
 'though': 6844,
 'fun': 3020,
 'bar': 1207,
 'sound': 6308,
 'callin': 1597,
 'say': 5899,
 'bruv': 1516,
 'certainly': 1695,
 'puts': 5480,
 'things': 6825,
 'perspective': 5139,
 'happens': 3316,
 'tot': 6975,
 'liao': 4082,
 'shirt': 6071,
 'believe': 1292,
 'attached': 1109,
 'seeing': 5961,
 'teach': 6711,
 'midnight': 4450,
 'miss': 4490,
 'already': 909,
 'let': 4076,
 'send': 5984,
 'money': 4549,
 'towards': 6983,
 'want': 7362,
 'crave': 2039,
 'current': 2097,
 'food': 2912,
 'lingo': 4117,
 'wot': 7590,
 'earth': 2487,
 'finished': 2841,
 'making': 4312,
 'honey': 3464,
 'sweetheart': 6627,
 'darling': 2141,
 'buns': 1540,
 'sugar': 6554,
 'plum': 5226,
 'loverboy': 4214,
 'boytoy': 1458,
 'smacks': 6213,
 'ass': 1086,
 'gym': 3270,
 'same': 5865,
 'question': 5495,
 'email': 2552,
 'alertfrom': 886,
 'jeri': 3804,
 'stewartsize': 6443,
 '2kbsubject': 391,
 'low': 4220,
 'prescripiton': 5352,
 'drvgsto': 2450,
 'listen': 4127,
 '123': 274,
 'should': 6095,
 'come': 1889,
 'al': 878,
 'above': 752,
 'brought': 1508,
 'sun': 6569,
 'shiny': 6067,
 'down': 2405,
 'warming': 7369,
 'heart': 3365,
 'putting': 5482,
 'constant': 1959,
 'smile': 6225,
 'face': 2725,
 'loved': 4209,
 'cared': 1636,
 'todays': 6923,
 'voda': 7297,
 'numbers': 4828,
 'ending': 2567,
 '7548': 609,
 '350': 440,
 'please': 5218,
 '08712300220': 96,
 'quoting': 5508,
 'code': 1861,
 '4041': 475,
 'standard': 6405,
 'rates': 5545,
 'app': 1001,
 'happening': 3315,
 'gotten': 3190,
 'job': 3819,
 'begun': 1286,
 'registration': 5643,
 'permanent': 5126,
 'residency': 5706,
 'rubber': 5814,
 'place': 5198,
 'another': 965,
 'number': 4827,
 'does': 2359,
 'dance': 2130,
 'river': 5768,
 'wun': 7621,
 'msg': 4595,
 'anything': 986,
 'valuable': 7226,
 'situations': 6167,
 'before': 1281,
 'second': 5947,
 'loosing': 4186,
 'work': 7574,
 'yet': 7674,
 'surely': 6597,
 'dont': 2385,
 'forgot': 2930,
 'touch': 6978,
 'done': 2383,
 'oredi': 4953,
 'house': 3501,
 'maid': 4300,
 'murderer': 4630,
 'murdered': 4629,
 'th': 6777,
 'january': 3782,
 'as': 1068,
 'public': 5455,
 'govt': 3193,
 'instituitions': 3688,
 'closed': 1832,
 'including': 3643,
 'post': 5296,
 'office': 4872,
 'understand': 7124,
 'textbuddy': 6769,
 'chat': 1728,
 'horny': 3484,
 'guys': 3267,
 'area': 1031,
 '25p': 364,
 'search': 5942,
 'postcode': 5299,
 'gaytextbuddy': 3072,
 '89693': 703,
 'sure': 6596,
 'leave': 4053,
 'min': 4461,
 'decimal': 2179,
 'amp': 936,
 'problem': 5393,
 'cann': 1619,
 'voice': 7300,
 'asa': 1069,
 'airport': 870,
 'satsgettin': 5889,
 '47per': 501,
 'hour': 3498,
 'means': 4392,
 'lie': 4089,
 'keep': 3897,
 'lost': 4195,
 'pounds': 5308,
 'since': 6143,
 'doc': 2350,
 'visit': 7288,
 'woot': 7569,
 'stuffing': 6513,
 'logo': 4163,
 'lover': 4213,
 'names': 4664,
 'joined': 3827,
 'name1': 4661,
 'name2': 4662,
 'mobno': 4530,
 'adam': 796,
 '07123456789': 26,
 '87077': 683,
 'yahoo': 7649,
 'pobox36504w45wq': 5241,
 'txtno': 7080,
 'ads': 814,
 '150p': 294,
 'prashanthettan': 5332,
 'mother': 4573,
 'passed': 5070,
 'pray': 5333,
 'hope': 3474,
 'alright': 910,
 'worry': 7584,
 'might': 4452,
 'felt': 2793,
 'bit': 1351,
 'desparate': 2243,
 'learned': 4051,
 'fake': 2740,
 'waiting': 7340,
 'alfie': 890,
 'moon': 4562,
 'children': 1770,
 'song': 6284,
 'mob': 4524,
 'm8s': 4271,
 'tone': 6942,
 'charity': 1720,
 'nokias': 4781,
 'poly': 5261,
 'polys': 5266,
 'zed': 7719,
 '08701417012': 71,
 'profit': 5408,
 '1st': 329,
 'no1': 4771,
 'txting': 7079,
 'mates': 4363,
 'getzed': 3108,
 'co': 1850,
 '36504': 444,
 'w4': 7324,
 '5wq': 562,
 'norm': 4791,
 'congrats': 1946,
 'year': 7661,
 'cinema': 1798,
 'pass': 5068,
 'yours': 7697,
 '09061209465': 179,
 'suprman': 6594,
 'matrix3': 4370,
 'starwars3': 6421,
 'etc': 2632,
 'bx420': 1569,
 'ip4': 3719,
 '5we': 561,
 '150pm': 296,
 'lemme': 4066,
 'goin': 3154,
 'met': 4442,
 'alex': 889,
 'nichols': 4744,
 'middle': 4449,
 'school': 5913,
 'turns': 7064,
 'dealing': 2165,
 'hello': 3382,
 'madam': 4286,
 'ride': 5750,
 'equally': 2606,
 'uneventful': 7129,
 'those': 6841,
 'pesky': 5140,
 'cyclists': 2118,
 'freemsg': 2970,
 'these': 6814,
 'video': 7266,
 'pic': 5167,
 'fones': 2910,
 'wild': 7497,
 'hurry': 3543,
 'bored': 1422,
 'rcvd': 5557,
 'stop2stop': 6464,
 'guaranteed': 3247,
 'yr': 7703,
 'representative': 5695,
 '08714712379': 114,
 'between': 1316,
 '10am': 254,
 've': 7242,
 'fixed': 2860,
 'test': 6761,
 'message': 4435,
 'there': 6812,
 'contacted': 1962,
 'entered': 2589,
 'find': 2834,
 'landline': 3996,
 '09111032124': 243,
 'pobox12n146tf150p': 5238,
 'lol': 4168,
 'air': 869,
 'balloon': 1195,
 'treasure': 7010,
 'moment': 4543,
 'spend': 6346,
 'pansy': 5034,
 'living': 4140,
 'jungle': 3858,
 'two': 7071,
 'worried': 7582,
 'about': 750,
 'greatest': 3218,
 'courage': 2016,
 'bear': 1256,
 'defeat': 2194,
 'losing': 4193,
 'tc': 6706,
 'private': 5383,
 '2004': 342,
 'statement': 6424,
 '07742676969': 30,
 'shows': 6107,
 '786': 615,
 'unredeemed': 7152,
 'points': 5253,
 '08719180248': 146,
 'identifier': 3581,
 '45239': 497,
 'expires': 2704,
 'dinner': 2302,
 'rite': 5766,
 'confirm': 1940,
 'wif': 7491,
 'tones': 6943,
 'include': 3641,
 'mcfly': 4385,
 'ab': 741,
 'sara': 5875,
 'jorge': 3840,
 'shock': 6079,
 'smith': 6229,
 'switch': 6636,
 'order': 4950,
 'follow': 2902,
 'instructions': 3689,
 'next': 4739,
 'hear': 3361,
 'sad': 5844,
 'story': 6475,
 'nt': 4818,
 'wish': 7522,
 'parents': 5052,
 'kids': 3923,
 'went': 7444,
 'colleagues': 1873,
 'electricity': 2543,
 'fml': 2896,
 'sister': 6158,
 'earn': 2484,
 'shore': 6087,
 'takin': 6671,
 'bus': 1550,
 'moan': 4523,
 'thin': 6823,
 'goes': 3151,
 'wrong': 7609,
 'arguments': 1041,
 'fed': 2781,
 'himso': 3419,
 'bother': 1431,
 'hav': 3339,
 '2go': 387,
 'thanx': 6787,
 'xx': 7635,
 'makes': 4309,
 'thk': 6835,
 'fall': 2742,
 'actually': 794,
 'prone': 5424,
 'falls': 2744,
 'lucky': 4238,
 'fetch': 2796,
 'gentle': 3090,
 'princess': 5376,
 'make': 4308,
 'tarot': 6688,
 'texts': 6775,
 'try': 7040,
 '85555': 674,
 'msgs': 4601,
 'each': 2479,
 'dislikes': 2328,
 'bed': 1269,
 'friends': 2983,
 'imma': 3615,
 'flip': 2878,
 'shit': 6073,
 'half': 3287,
 'notice': 4807,
 'looking': 4180,
 'mirror': 4483,
 'youre': 7694,
 'turning': 7063,
 'freak': 2958,
 'sorry': 6299,
 'bathroom': 1232,
 'sup': 6580,
 'jus': 3860,
 'finish': 2839,
 'blowing': 1387,
 'yoyyooo': 7702,
 'permissions': 5128,
 'drive': 2432,
 'mac': 4277,
 'usb': 7195,
 'flash': 2867,
 'omg': 4903,
 'cat': 1665,
 'worms': 7581,
 'bad': 1181,
 'end': 2565,
 'long': 4173,
 'applebees': 1006,
 'squatting': 6385,
 'walking': 7348,
 'dint': 2304,
 'us': 7193,
 '09061743810': 190,
 'abta': 757,
 'complimentary': 1919,
 'tenerife': 6745,
 '5000': 531,
 'await': 1151,
 'collection': 1877,
 'sae': 5845,
 '326': 437,
 'cw25wx': 2116,
 '150': 292,
 'ppm': 5316,
 'teams': 6716,
 'freephone': 2971,
 '0808': 55,
 '145': 288,
 '4742': 500,
 '9am': 728,
 '11pm': 268,
 'specific': 6336,
 'ac': 761,
 'sun0819': 6570,
 'posts': 5302,
 'seem': 5963,
 'wanted': 7364,
 '62468': 571,
 'okay': 4886,
 'booked': 1412,
 'bugis': 1534,
 '08715205273': 122,
 'que': 5492,
 'pases': 5067,
 'un': 7110,
 'buen': 1530,
 'tiempo': 6875,
 'took': 6955,
 ...}

In [24]:
X_train_np=X_train_cv.toarray()
X_train_np[0]

array([0, 0, 0, ..., 0, 0, 0])

In [25]:
np.where(X_train_np[0]!=0)

(array([1331, 2264, 3341, 4236, 6253, 6265, 6898, 6916, 7403, 7499, 7502]),)

#Naive Based classifier

In [27]:
model=MultinomialNB()
model.fit(X_train_cv,y_train)

MultinomialNB()

In [28]:
y_pred=model.predict(X_test_cv)

In [31]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       970
           1       0.94      0.94      0.94       145

    accuracy                           0.98      1115
   macro avg       0.97      0.97      0.97      1115
weighted avg       0.98      0.98      0.98      1115

In [32]:
message={"upto 20% of offer on parking"}

In [34]:
msg_cnt=v.transform(message)
model.predict(msg_cnt)

array([1])