<a href="https://colab.research.google.com/github/AishwaryaGhorpade/Data-Science/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# New Section

In [2]:
import pandas as pd

In [3]:
df=pd.read_csv('sample_data/mnist_test.csv')
#df=pd.read_excel('xyz.xlsx',sheet_name='Page 1')

In [4]:
df.head()   #by default it give top 5 value

,7,0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,...,0.658,0.659,0.660,0.661,0.662,0.663,0.664,0.665,0.666,0.667
0,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [5]:
df.head(10)

,7,0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,...,0.658,0.659,0.660,0.661,0.662,0.663,0.664,0.665,0.666,0.667
0,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [6]:
df.tail()

,7,0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,...,0.658,0.659,0.660,0.661,0.662,0.663,0.664,0.665,0.666,0.667
9994,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9995,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9996,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9997,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9998,6,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [7]:
df.tail(10)

,7,0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,...,0.658,0.659,0.660,0.661,0.662,0.663,0.664,0.665,0.666,0.667
9989,7,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9990,8,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9991,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9992,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9993,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9994,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9995,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9996,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9997,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9998,6,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9999 entries, 0 to 9998
Columns: 785 entries, 7 to 0.667
dtypes: int64(785)
memory usage: 59.9 MB

In [9]:
df.describe()

,7,0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,...,0.658,0.659,0.660,0.661,0.662,0.663,0.664,0.665,0.666,0.667
count,9999.000000,9999.0,9999.0,9999.0,9999.0,9999.0,9999.0,9999.0,9999.0,9999.0,...,9999.000000,9999.000000,9999.000000,9999.000000,9999.0,9999.0,9999.0,9999.0,9999.0,9999.0
mean,4.443144,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.179318,0.163616,0.052605,0.000600,0.0,0.0,0.0,0.0,0.0,0.0
std,2.895897,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,5.674433,5.736359,2.420125,0.060003,0.0,0.0,0.0,0.0,0.0,0.0
min,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
25%,2.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
50%,4.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
75%,7.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
max,9.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,253.000000,253.000000,156.000000,6.000000,0.0,0.0,0.0,0.0,0.0,0.0

In [10]:
df.columns

Index(['7', '0', '0.1', '0.2', '0.3', '0.4', '0.5', '0.6', '0.7', '0.8',
       ...
       '0.658', '0.659', '0.660', '0.661', '0.662', '0.663', '0.664', '0.665',
       '0.666', '0.667'],
      dtype='object', length=785)

In [11]:
df.T  #Transpose Matrix

,0,1,2,3,4,5,6,7,8,9,...,9989,9990,9991,9992,9993,9994,9995,9996,9997,9998
7,2,1,0,4,1,4,9,5,9,0,...,7,8,9,0,1,2,3,4,5,6
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
0.1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
0.2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
0.3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0.663,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
0.664,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
0.665,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
0.666,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
0.667,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [12]:
df.sort_values('7')  #sort based on 7 column value

,7,0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,...,0.658,0.659,0.660,0.661,0.662,0.663,0.664,0.665,0.666,0.667
9961,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9963,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4156,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4165,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2857,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2856,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6038,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9991,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [13]:
df['7']  #print specific column or df.column_Name

0       2
1       1
2       0
3       4
4       1
       ..
9994    2
9995    3
9996    4
9997    5
9998    6
Name: 7, Length: 9999, dtype: int64

In [14]:
df['7']+1000  #modifing values

0       1002
1       1001
2       1000
3       1004
4       1001
        ...
9994    1002
9995    1003
9996    1004
9997    1005
9998    1006
Name: 7, Length: 9999, dtype: int64

In [15]:
df['new value of 7']=df['7']+1000  #adding new column to end of the dataframe

In [16]:
df.head(5)

,7,0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,...,0.659,0.660,0.661,0.662,0.663,0.664,0.665,0.666,0.667,new value of 7
0,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1002
1,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1001
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1000
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1004
4,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1001

In [17]:
df['new column']='Good day'

In [18]:
df.head(5)

,7,0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,...,0.660,0.661,0.662,0.663,0.664,0.665,0.666,0.667,new value of 7,new column
0,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1002,Good day
1,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1001,Good day
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1000,Good day
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1004,Good day
4,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1001,Good day

In [19]:
#how to access some rows
df[10:15]

,7,0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,...,0.660,0.661,0.662,0.663,0.664,0.665,0.666,0.667,new value of 7,new column
10,6,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1006,Good day
11,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1009,Good day
12,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1000,Good day
13,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1001,Good day
14,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1005,Good day

In [20]:
df[df['new value of 7'] > 2000]

Empty DataFrame
Columns: [7, 0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 0.10, 0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.20, 0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.30, 0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.40, 0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.50, 0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.60, 0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.70, 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.80, 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.90, 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, ...]
Index: []

[0 rows x 787 columns]

In [21]:
total=df[df['new value of 7'] > 1001]

In [22]:
total

,7,0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,...,0.660,0.661,0.662,0.663,0.664,0.665,0.666,0.667,new value of 7,new column
0,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1002,Good day
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1004,Good day
5,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1004,Good day
6,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1009,Good day
7,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1005,Good day
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9994,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1002,Good day
9995,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1003,Good day
9996,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1004,Good day
9997,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1005,Good day
9998,6,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1006,Good day

In [23]:
df['7'].fillna(15)  #fill the null values

0       2
1       1
2       0
3       4
4       1
       ..
9994    2
9995    3
9996    4
9997    5
9998    6
Name: 7, Length: 9999, dtype: int64

In [24]:
#remove column
df.pop('0.1')

0       0
1       0
2       0
3       0
4       0
       ..
9994    0
9995    0
9996    0
9997    0
9998    0
Name: 0.1, Length: 9999, dtype: int64

In [25]:
df.head(3)  #check 0.1 is removed

,7,0,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,...,0.660,0.661,0.662,0.663,0.664,0.665,0.666,0.667,new value of 7,new column
0,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1002,Good day
1,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1001,Good day
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1000,Good day

In [26]:
df['new value of 7'].head(5)

0    1002
1    1001
2    1000
3    1004
4    1001
Name: new value of 7, dtype: int64

In [27]:
import numpy as np
df['new value of 7'].apply(np.sqrt).head(5)   #apply method helps to apply ome maths function

0    31.654384
1    31.638584
2    31.622777
3    31.685959
4    31.638584
Name: new value of 7, dtype: float64

concat and Merging

In [37]:
df1=pd.DataFrame({
    'A':['A0','A1','A2','A3'],
    'B':['B0','B1','B2','B3'],
    'C':['C0','C1','C2','C3'],
    'D':['D0','D1','D2','D3']
})
df2=pd.DataFrame({
    'E':['A4','A5','A6','A7'],
    'F':['B4','B5','B6','B7'],
    'C':['C0','C3','C6','C7'],
    'G':['D4','D5','D6','D7']
})

In [38]:
df1

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [39]:
df2

    E   F   C   G
0  A4  B4  C0  D4
1  A5  B5  C3  D5
2  A6  B6  C6  D6
3  A7  B7  C7  D7

In [40]:
merge_df=pd.merge(df1,df2,on='C', how='outer')

In [41]:
merge_df

     A    B   C    D    E    F    G
0   A0   B0  C0   D0   A4   B4   D4
1   A1   B1  C1   D1  NaN  NaN  NaN
2   A2   B2  C2   D2  NaN  NaN  NaN
3   A3   B3  C3   D3   A5   B5   D5
4  NaN  NaN  C6  NaN   A6   B6   D6
5  NaN  NaN  C7  NaN   A7   B7   D7

In [43]:
merge_df1=pd.merge(df1,df2,on='C', how='inner')

In [44]:
merge_df1

    A   B   C   D   E   F   G
0  A0  B0  C0  D0  A4  B4  D4
1  A3  B3  C3  D3  A5  B5  D5

In [45]:
merge_df2=pd.merge(df1,df2,on='C', how='left')

In [46]:
merge_df2

    A   B   C   D    E    F    G
0  A0  B0  C0  D0   A4   B4   D4
1  A1  B1  C1  D1  NaN  NaN  NaN
2  A2  B2  C2  D2  NaN  NaN  NaN
3  A3  B3  C3  D3   A5   B5   D5

In [47]:
merge_df3=pd.merge(df1,df2,on='C', how='right')

In [48]:
merge_df3

     A    B   C    D   E   F   G
0   A0   B0  C0   D0  A4  B4  D4
1   A3   B3  C3   D3  A5  B5  D5
2  NaN  NaN  C6  NaN  A6  B6  D6
3  NaN  NaN  C7  NaN  A7  B7  D7

loc and iloc

In [49]:
s=pd.Series(list("abcdef"),index=[49,48,47,0,1,2])
s

49    a
48    b
47    c
0     d
1     e
2     f
dtype: object

In [50]:
s.loc[0]  #value at index lable 0

'd'

In [51]:
s.iloc[0]   #vaue at 0th index i.e 'a'

'a'

In [52]:
s.loc[0:1]  #rows at index labels btw 0-1(inclusive)

0    d
1    e
dtype: object

In [53]:
s.iloc[0:1]   #rows at index value btw 0-1(exclusive)

49    a
dtype: object